import './styles/globals.css'

import localFont from 'next/font/local'

import Header from './components/Header'
import Footer from './components/Footer'

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app'
}

const raleway = localFont({
  src: "./fonts/Raleway-Regular.ttf"
})

export default function RootLayout({ children }) {

  return (
    <html lang="en" className={raleway.className} >
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
